spring:
  application:
    name: traceability-service
#   datasource:
#     url: 
#     username: 
#     password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: 

server:
  port: 8082