spring:
  application:
    name: traceability-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: <db>

my-app:
  security:
    jwt:
      secret-key: aa51197e3861ba9d8e7d3add5f2bc30862c891e0a3762935c8b8ecf6a61a9994

server:
  port: 8082

springdoc:
  swagger-ui:
    path: /swagger-ui.html